{% set name = "et-xmlfile" %}
{% set version = "1.1.0" %}
{% set sha256 = "8eb9e2bc2f8c97e37a2dc85a09ecdcdec9d8a396530a6d5a33b30b9a92da0c5c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name | replace("-", "_") }}/{{ name | replace("-", "_") }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python
  run:
    - python
    - lxml >=3.4

test:
  imports:
    - et_xmlfile

about:
  home: https://bitbucket.org/openpyxl/et_xmlfile
  license: MIT
  license_family: MIT
  license_file: {{ environ["RECIPE_DIR"] }}/LICENCE.rst
  summary: An implementation of lxml.xmlfile for the standard library.

extra:
  recipe-maintainers:
    - npavlovikj
